### ISSUE TITLE
Error on getRequests

### ISSUE THREAD

**Issue by gab8** [uecasm/colony4cc#6]
Hi.

When trying to run getRequests on a server I'm getting the following error:

[11:11:00] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
[11:11:00] [Server thread/ERROR] [computercraft/]: Error running task
java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.23.jar:36.1] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291] {}
        at com.buuz135.industrial.item.infinity.ItemInfinity.getDurabilityForDisplay(ItemInfinity.java:198) ~[industrialforegoing:3.2.11] {re:classloading}
        at dan200.computercraft.shared.peripheral.generic.data.ItemData.fill(ItemData.java:66) ~[computercraft:1.95.3] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion$MinecraftConverter.convertStack(LuaConversion.java:123) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion$MinecraftConverter.convert(LuaConversion.java:77) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion.convert(LuaConversion.java:37) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion$CollectionConverter.convert(LuaConversion.java:58) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion.convert(LuaConversion.java:37) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion$CollectionConverter.lambda$convert$0(LuaConversion.java:51) ~[colony4cc:1.2.1] {re:classloading}
        at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_291] {}
        at nz.co.mirality.colony4cc.LuaConversion$CollectionConverter.convert(LuaConversion.java:51) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion.convert(LuaConversion.java:37) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion$CollectionConverter.convert(LuaConversion.java:58) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.LuaConversion.convert(LuaConversion.java:37) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.peripheral.ColonyPeripheral.getRequests(ColonyPeripheral.java:368) ~[colony4cc:1.2.1] {re:classloading}
        at nz.co.mirality.colony4cc.peripheral.ColonyPeripheral$cc$getRequests20.apply(CC generated method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at dan200.computercraft.core.asm.PeripheralMethod.lambda$null$0(PeripheralMethod.java:21) ~[computercraft:1.95.3] {re:classloading}
        at dan200.computercraft.core.lua.CobaltLuaMachine$CobaltLuaContext.lambda$issueMainThreadTask$0(CobaltLuaMachine.java:522) ~[computercraft:1.95.3] {re:classloading}
        at dan200.computercraft.core.computer.MainThreadExecutor.execute(MainThreadExecutor.java:143) ~[computercraft:1.95.3] {re:classloading}
        at dan200.computercraft.core.computer.MainThread.executePendingTasks(MainThread.java:157) ~[computercraft:1.95.3] {re:classloading}
        at dan200.computercraft.shared.proxy.ComputerCraftProxyCommon$ForgeHandlers.onServerTick(ComputerCraftProxyCommon.java:121) ~[computercraft:1.95.3] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_659_ForgeHandlers_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:115) ~[forge:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:785) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}

Thanks

**Comment by gab8** [comment]
This is for the modpack Valhelsia 3 if that matters.

**Comment by uecasm** [comment]
That looks like a bug in Industrial Foregoing, specifically in its `ItemInfinity`.  It's doing something client-side-only on the server side; you should report it to them.  (Or check if there's a newer update that the modpack doesn't have yet.)

(It won't be unique to this mod, the same thing would likely happen if you dropped it into a chest and tried to use the standard CC inventory reading APIs.)
